
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 09 21:56:35 GMT-04:00 2015
//----------------------------------------------------

package l2_analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 3;
  public static final int CLAUSURA = 7;
  public static final int UNION = 6;
  public static final int LETRA = 10;
  public static final int CPARTENTESIS = 5;
  public static final int EOF = 0;
  public static final int BINARIO = 2;
  public static final int ESPACIO = 9;
  public static final int APARTENTESIS = 4;
  public static final int error = 1;
  public static final int COMENTARIO = 11;
  public static final int CONCATENACION = 8;
}

